//Tratando e lançando erros (try, catch, finally) (21/12/2022)

/*try{
  //é executada quando não há erros
  console.log('Abri um arquivo');
  console.log('Manipulei o arquivo e gerou erro');
  console.log('Fechei o arquivo');
}catch (err) {
  //é executada quando há erros
  console.log('Tratando o erro')
}finally{
  //Sempre (independente se ocorreu o erro ou não)
  console.log('Eu sempre sou executado')
}*/

